// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-7Ef5n9c2Ci-R5-RRmD7leOGTHtetjo',
    appId: '1:17666642853:web:568a3da8feabb3a6a08e4c',
    messagingSenderId: '17666642853',
    projectId: 'om-mcms-app',
    authDomain: 'om-mcms-app.firebaseapp.com',
    storageBucket: 'om-mcms-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IPQr37Siy_KrHEExhQyRgZFNbhNaZBI',
    appId: '1:17666642853:android:0c657e79a1f5d037a08e4c',
    messagingSenderId: '17666642853',
    projectId: 'om-mcms-app',
    storageBucket: 'om-mcms-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAQM6SNeK2NFKyy_iEt1n1Gi8C_sWsLt8',
    appId: '1:17666642853:ios:909912b802dd8a8da08e4c',
    messagingSenderId: '17666642853',
    projectId: 'om-mcms-app',
    storageBucket: 'om-mcms-app.appspot.com',
    iosBundleId: 'com.example.myMcms',
  );
}
